In [ ]:
import numpy as np

In [10]:
def single_concept(col,content):
    k = 1
    concept =''
    for i in col:
        concept += f'({i}'+f'[{content}])'
        if k <len(col):
            concept+= ' OR '
        k+=1
    if len(col) ==1:
        return concept
    else:
        return f'({concept})'
def bw_concept(concept1, concept2,connection):
    return f'({concept1} {connection} {concept2})'

def all_concept(listcc,connections):
    query = listcc[0]
    for cc, cn in zip(listcc[1:], connections):
        query = bw_concept(query, cc, cn)
    return query
        


def term_listing(str):
    return str.split(',')


In [52]:
#DONE
exerc = "exercise*,physical activit*,outdoor exposure,sport*"
negcoping = 'negative coping,negative coping behavior*,substance abuse*,alcohol,drinking'
poscoping = 'positive thought*,positive thinking'
wfh = 'work from home,home-based job, home-based work,work at home,remote work*'
physdist = 'physical distancing,physical distance,1*5 meters'
socialOnl = 'social online,socializing online,online contact,online connection*,virtual contact,virtual interaction*,non–face-to-face social interaction*,non–face-to-face contact,remote contact,digital technology use,electronic contact,electronic social contact,electronic interaction,video-based communication,video-based interaction'
travel = 'traveling,travel,vacation*,holiday'
socialize = 'socializing,socialize,meet friend*,meet people,meeting people,meeting friend*,social interact*,social contact,face*to*face contact,face*to*face interaction*,in*person contact,in*person interaction*,physical contact'

# Pending
seek_help = 'socially connected,social support,social cohesion'
stayathome = 'self*isolation,self-confinement,quarantined,in quarantine,quarantine,social isolation'


mh = "mental health,depression,depressed,depress*"
covid = "covid*,SARS-CoV-2,NCOV,sars-cov-2,coronavirus,lockdown*,lockdown polic*,pandemic"

meta = 'meta-analysis,meta analysis'


exerc = single_concept(term_listing(exerc), 'Title')
negcoping = single_concept(term_listing(negcoping), 'Title/Abstract')
poscoping = single_concept(term_listing(poscoping), 'Title/Abstract')
wfh = single_concept(term_listing(wfh), 'Title/Abstract')
physdist =single_concept(term_listing(physdist), 'Title/Abstract')
socialOnl = single_concept(term_listing(socialOnl), 'Title/Abstract')
travel = single_concept(term_listing(travel), 'Title/Abstract')
socialize = single_concept(term_listing(socialize), 'Title/Abstract')

seek_help = single_concept(term_listing(seek_help), 'Title/Abstract')
stayathome = single_concept(term_listing(stayathome), 'Title/Abstract')

mh = single_concept(term_listing(mh), 'Title')
covid = single_concept(term_listing(covid), 'Title/Abstract')
meta = single_concept(term_listing(meta), 'Title/Abstract')

query = all_concept([stayathome,mh, covid],['AND', 'AND'])

# Travel
# query = all_concept([travel,mh],['AND'])
query



'((((self*isolation[Title/Abstract]) OR (self-confinement[Title/Abstract]) OR (quarantined[Title/Abstract]) OR (in quarantine[Title/Abstract]) OR (quarantine[Title/Abstract]) OR (social isolation[Title/Abstract])) AND ((mental health[Title]) OR (depression[Title]) OR (depressed[Title]) OR (depress*[Title]))) AND ((covid*[Title/Abstract]) OR (SARS-CoV-2[Title/Abstract]) OR (NCOV[Title/Abstract]) OR (sars-cov-2[Title/Abstract]) OR (coronavirus[Title/Abstract]) OR (lockdown*[Title/Abstract]) OR (lockdown polic*[Title/Abstract]) OR (pandemic[Title/Abstract])))'

### Extract data from Regression


In [25]:
input_text = """-0.109
-0.092
0.128
0.065
-0.212
;

-0.573

;
-0.229
0.430
;

0.232
;
-0.415

;
-0.124
-0.200
;

0.218

;
-0.249
;

0.173
0.066
0.110
0.065
;
-0.736
-0.319
0.255
0.576

;
0.523
;

3.987
;
-0.051
-0.051
0.042

;
0.580
0.196
-0.064
-0.049
;

-0.096
-0.130
;
-3.618
"""

dimension = [6,2,3,2,2,3,2,2,5,5,2,2,4,5,2,1]
# Split the input text into individual values

data = input_text.split(";")
result = []
for i, gr in enumerate(data):
   gr_data = gr.strip().split()
   missing = dimension[i]-len(gr_data)
   result += ["0"]*missing+gr_data
row = ";".join(result)
print(row)

0;-0.109;-0.092;0.128;0.065;-0.212;0;-0.573;0;-0.229;0.430;0;0.232;0;-0.415;0;-0.124;-0.200;0;0.218;0;-0.249;0;0.173;0.066;0.110;0.065;0;-0.736;-0.319;0.255;0.576;0;0.523;0;3.987;0;-0.051;-0.051;0.042;0;0.580;0.196;-0.064;-0.049;-0.096;-0.130;-3.618


In [16]:
data

['-0.109\n-0.092\n0.128\n0.065\n-0.212\n',
 '\n\n-0.573\n\n',
 '\n-0.229\n0.430\n',
 '\n\n0.232\n-0.415\n\n',
 '\n-0.124\n-0.200\n',
 '\n\n0.218\n\n',
 '\n-0.249\n',
 '\n\n0.173\n0.066\n0.110\n0.065\n',
 '\n-0.736\n-0.319\n0.255\n0.576\n\n',
 '\n0.523\n',
 '\n\n3.987\n',
 '\n-0.051\n-0.051\n0.042\n\n',
 '\n0.580\n0.196\n-0.064\n-0.049\n',
 '\n\n-0.096\n-0.130\n',
 '\n-3.618\n']

In [14]:
len(data)

15

In [9]:
len(dimension)

17

In [4]:
import pandas as pd
import numpy as np

In [1]:
27**(1/3)

3.0

In [4]:
a = []
a.extend(range(2))
a.extend([2]*3)
a

[0, 1, 2, 2, 2]

In [2]:
import pandas as pd
features = pd.Series([1,0,1,0,1,0,1], index = ['bs', 'age1', 'age2', 'vegetarian_no', 'vegetarian_yes', 'children_no', 'children_yes'])
status_var  ='vegetarian'
features["age1"]


0

In [9]:
def change_features(status, features):
    if status: 
        features[features.index.str.contains(pat = f'{status_var}')] = [0,1]
    else:
        features[features.index.str.contains(pat = f'{status_var}')] = [1,0]   

status = False
change_features(status, features)

In [3]:
import pandas as pd

In [4]:
class agent():
    def __init__(self, status, features, status_var):
        self.status = status
        self.features = features
        self.status_var = status_var
    
    def change_features(self):
        if self.status: 
            self.features[self.features.index.str.contains(pat = f'{self.status_var}')] = [0,1]
        else:
            self.features[self.features.index.str.contains(pat = f'{self.status_var}')] = [1,0]   

    

In [5]:
features = pd.Series([1,0,1,0,1,0,1], index = ['bs', 'age1', 'age2', 'vegetarian_no', 'vegetarian_yes', 'children_no', 'children_yes'])
status = False
status_var  ='vegetarian'
features

bs                1
age1              0
age2              1
vegetarian_no     0
vegetarian_yes    1
children_no       0
children_yes      1
dtype: int64

In [8]:
agent1 = agent(False, features, status_var)
agent1.change_features()
agent1.features

bs                1
age1              0
age2              1
vegetarian_no     1
vegetarian_yes    0
children_no       0
children_yes      1
dtype: int64

In [25]:
dict_ = {True:'r', False : 'g'}
dict_[True]

'r'

In [33]:
import random

seed = random.getrandbits(128)
random.Random(seed)

In [34]:
import numpy as np
tuple(np.array([1,3])+np.array([-2,2]))

(-1, 5)

In [122]:
import pandas as pd
import numpy as np
features = pd.Series([1,0,1,0,1,0,1], index = ['bs', 'age1', 'age2', 'vegetarian_no', 'vegetarian_yes', 'children_no', 'children_yes'])
neigbors1 = pd.DataFrame(data = { 'bs':[1, 0.5, 0],
                          'age1' :[0.1, 0.2, 0], 
                          'age2':[0.1, 0.2, 0.3], 
                          'vegetarian_no':[0.1, 0.2,0], 
                          'vegetarian_yes':[0.1,0.2,0],
                          'children_no' :[0.1,0.2,0],
                          'children_yes':[0.1,0.2,0],
                         'actions' : ['moving', 'veg', 'om']}).set_index('actions')
neigbors2 = pd.DataFrame(data = { 'bs':[1, 0, 0.5],
                          'age1' :[0.1, 0, 0.3], 
                          'age2':[0.1, 0, 0.3], 
                          'vegetarian_no':[0.1, 0,0.3], 
                          'vegetarian_yes':[0.1,0,0.3],
                          'children_no' :[0.1,0,0.3],
                          'children_yes':[0.4,0,0.3],
                         'actions' : ['moving', 'veg', 'om']}).set_index('actions')
prfs = [neigbors1,neigbors2]
result = np.array(prfs).dot(features)
print(result)
print(result[:, mask])

mask = np.isin(neigbors1.index, [])

# Index the columns based on the mask
_neigh_score_move = np.sum(result[:, mask])
print(_neigh_score_move)


[[1.3 1.1 0.3]
 [1.6 0.  1.4]]
[[1.3]
 [1.6]]
0.0


In [16]:
neigbors1.index

Index(['moving', 'veg', 'om'], dtype='object', name='actions')

In [34]:
sum([0.36, 0.31, 0.17, 0.15, 0.01])

1.0

In [ ]:
"""-4.28391981
0.095615284
0.346503212
0.034807466
-0.477086146
0.015070726
1.015501064
-0.466270405
-0.204207655
-0.360253913
-0.427038465
0.380751044
0.790711968
-0.049356888
-0.646125257
0.948016543
-0.948176727
0.536693187
0.055711864
-0.565934092
0.263342013
-0.68801958
0.487015224"""


In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
a= np.array([0.189, 0.166, 0.093, 0.073, 0.007])
np.round(a/a.sum(), 3)


array([0.358, 0.314, 0.176, 0.138, 0.013])

In [7]:
choice = [2,-2]
np.array([random.choice(choice), random.choice(choice), random.choice(choice)])

array([ 2,  2, -2])

In [17]:
result_nw = [p.dot(features) for p in prfs]
result_nw

[actions
 moving    1.3
 veg       1.1
 om        0.3
 dtype: float64,
 actions
 moving    1.5
 veg       0.0
 om        1.4
 dtype: float64]

In [79]:
prfs_a= np.array(prfs)
prfs_a

array([[[1. , 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
        [0.5, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
        [0. , 0. , 0.3, 0. , 0. , 0. , 0. ]],

       [[1. , 0.1, 0.1, 0.1, 0.1, 0.1, 0.3],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0.5, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]]])

In [92]:
np.finfo(np.longdouble).precision

15

In [98]:
params_self

bs  age1  age2  vegetarian_no  vegetarian_yes  children_no  \
actions                                                                
moving   1.0   0.1   0.1            0.1             0.1          0.1   
veg      0.0   0.0   0.0            0.0             0.0          0.0   
om       0.5   0.3   0.3            0.3             0.3          0.3   

         children_yes  
actions                
moving            0.3  
veg               0.0  
om                0.3

In [23]:
np.set_printoptions(precision=2)
params_self = pd.DataFrame(data = { 'bs':[1, 0, 0.5],
                          'age1' :[0.1, 0, 0.3], 
                          'age2':[0.1, 0, 0.3], 
                          'vegetarian_no':[0.1, 0,0.3], 
                          'vegetarian_yes':[0.1,0,0.3],
                          'children_no' :[0.1,0,0.3],
                          'children_yes':[0.3,0,0.3],
                         'actions' : ['moving', 'veg', 'om']}).set_index('actions')
params_self = params_self.astype(float)
features = pd.Series([1,0,1,0,1,0,1], index = ['bs', 'age1', 'age2', 'vegetarian_no', 'vegetarian_yes', 'children_no', 'children_yes'])
_score_self = np.array(params_self).dot(np.array(features))
mask = np.isin(params_self.index,['moving'])
print(_score_self)
print(params_self.index)
_sum_score_self_move = np.sum(_score_self[mask])
_sum_score_self = np.sum(_score_self)
_sum_score_self_move , _sum_score_self

[1.5 0.  1.4]
Index(['moving', 'veg', 'om'], dtype='object', name='actions')


(1.5000000000000002, 2.9000000000000004)

In [15]:
_neigh_scores = prfs_a.dot(features)
print(_neigh_scores)
actions_nw = neigbors1.index
nw_decisions_to_move = ['moving']

# Create a boolean mask for the selected labels
mask = np.isin(actions_nw, nw_decisions_to_move)

# Index the columns based on the mask
_neigh_score_move = np.sum(result[:, mask], axis = 1)
print(_neigh_score_move)

NameError: name 'prfs_a' is not defined

In [42]:
np.sum([1.3])

1.3

In [46]:
neigbors1

bs  age1  age2  vegetarian_no  vegetarian_yes  children_no  \
actions                                                                
moving   1.0   0.1   0.1            0.1             0.1          0.1   
veg      0.5   0.2   0.2            0.2             0.2          0.2   
om       0.0   0.0   0.3            0.0             0.0          0.0   

         children_yes  
actions                
moving            0.1  
veg               0.2  
om                0.0

In [96]:
params_self.columns

Index(['bs', 'age1', 'age2', 'vegetarian_no', 'vegetarian_yes', 'children_no',
       'children_yes'],
      dtype='object')

In [ ]:
np.dot


In [126]:
# test creating influecing profile (zero-out)by numpy
params_self = pd.DataFrame(data = { 'bs':[1, .4, 0.5],
                          'age1' :[0.1, 0.2, 0.3], 
                          'age2':[0.1, 0, 0.3], 
                          'vegetarian_no':[0.1, 0,0.3], 
                          'vegetarian_yes':[0.1,0,0.3],
                          'children_no' :[0.1,0.3,0.3],
                          'children_yes':[0.3,0.2,0.3],
                         'actions' : ['moving', 'veg', 'om']}).set_index('actions')

features = pd.Series([1,0,1,0,1,0,1], index = ['bs', 'age1', 'age2', 'vegetarian_no', 'vegetarian_yes', 'children_no', 'children_yes'])
_influencing_profile = np.multiply(np.array(params_self), np.array(features))

print(_influencing_profile)
masked_neg = np.isin(params_self.index, ['veg'])
_influencing_profile[masked_neg,:] =0
print(_influencing_profile)
print(_influencing_profile.dot(np.array(features)))
print(np.dot(_influencing_profile,np.array(features)))

[[1.  0.  0.1 0.  0.1 0.  0.3]
 [0.4 0.  0.  0.  0.  0.  0.2]
 [0.5 0.  0.3 0.  0.3 0.  0.3]]
[[1.  0.  0.1 0.  0.1 0.  0.3]
 [0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.3 0.  0.3 0.  0.3]]
[1.5 0.  1.4]
[1.5 0.  1.4]


In [125]:
def lowerlist(l):
    if len(l) ==0:
        return 
    else:
        
        return [e.lower() for e in l]
lowerlist([])

In [121]:
masked_neg, ~masked_neg

(array([False,  True, False]), array([ True, False,  True]))

In [116]:
_influencing_profile = np.array(params_self).multiply(np.array(features))

AttributeError: 'numpy.ndarray' object has no attribute 'multiply'

In [113]:
# TEST creating list of influencing profiles
def get_influencing_profile(profile, features):
    _influencing_profile = np.multiply(np.array(profile), np.array(features))
    masked_neg = np.isin(profile.index, ['veg', 'moving'])
    _influencing_profile[masked_neg,:] = 0
    return _influencing_profile
neigbors1 = pd.DataFrame(data = { 'bs':[1, 0.5, 0],
                          'age1' :[0.1, 0.2, 0], 
                          'age2':[0.1, 0.2, 0.3], 
                          'vegetarian_no':[0.1, 0.2,0], 
                          'vegetarian_yes':[0.1,0.2,0],
                          'children_no' :[0.1,0.2,0],
                          'children_yes':[0.1,0.2,0],
                         'actions' : ['moving', 'veg', 'om']}).set_index('actions')
neigbors2 = pd.DataFrame(data = { 'bs':[1, 0, 0.5],
                          'age1' :[0.1, 0, 0.3], 
                          'age2':[0.1, 0, 0.3], 
                          'vegetarian_no':[0.1, 0,0.3], 
                          'vegetarian_yes':[0.1,0,0.3],
                          'children_no' :[0.1,0,0.3],
                          'children_yes':[0.3,0,0.3],
                         'actions' : ['moving', 'veg', 'om']}).set_index('actions')
neighbors = [neigbors1, neigbors2]
features = pd.Series([1,0,1,0,1,0,1], index = ['bs', 'age1', 'age2', 'vegetarian_no', 'vegetarian_yes', 'children_no', 'children_yes'])
neigbors_pfs = [get_influencing_profile(n, features) for n in neighbors]
print(neigbors_pfs)
np.array(neigbors_pfs).dot(np.array(features))


[array([[0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.3, 0. , 0. , 0. , 0. ]]), array([[0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0. , 0.3, 0. , 0.3, 0. , 0.3]])]


array([[0. , 0. , 0.3],
       [0. , 0. , 1.4]])

In [24]:
np.argmin([5,6])

0

In [45]:
import numpy as np

a = np.array([[1.3, 1.1, 0.3],
              [1.3, 0.0, 1.4]])

labels = ['a', 'b', 'c']
selected_labels = ['a', 'c']

# Create a boolean mask for the selected labels
mask = np.isin(labels, selected_labels)

# Index the columns based on the mask
result = a[:, mask]

print(np.sum(result))

4.3


In [ ]:
prfs_a= np.array(prfs)
prfs_a

array([[[1. , 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
        [0.5, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
        [0. , 0. , 0.3, 0. , 0. , 0. , 0. ]],

       [[1. , 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0.5, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]]])

In [97]:
(1,2) + np.array([2,2])

array([3, 4])

In [74]:
pos = [tuple([1,2]), tuple([3,4])]

In [94]:
_week_pos = None
for i, nb in enumerate(prfs):
    if i == np.argmin(_score_to_move):
        _week_pos = pos[i]
        _choice = [2,-2]
        _path = np.array([random.choice(choice), random.choice(choice)])
        move_to_pos = tuple(_week_pos +_path)
    break
move_to_pos


(3, 0)

In [73]:
import random
choice = [2,-2]
path = np.array([random.choice(choice), random.choice(choice)])
path

array([-2, -2])

In [21]:
from math import log , exp

In [47]:
def homophily(p, pi, n):
    wi = pi
    si = pi*n
    di = 
    hi = ni/(pi +(1-pi)/3 )
    return (hi-wi)/(1-wi)

In [63]:
log(3/7)

-0.8472978603872037

In [62]:
get_p(-1.3)

0.2141650169574414

In [59]:
get_p(-2.1)

0.10909682119561294

In [55]:
get_p(3)

0.9525741268224333

In [49]:
log(0.84)

-0.1743533871447778

In [39]:
exp(2.44)

11.473040742794833

In [40]:
log(38/(100-38))

-0.4895482253187058

In [30]:
log(5.6)

1.7227665977411035

In [24]:
from math import exp
def get_p(sum_betas:float):
    '''logit reversed'''
    return exp(sum_betas)/(1+exp(sum_betas))

In [27]:

get_p(-1.44)

0.19154534856146752

In [ ]:
import networkx as nx
graph = nx.watts_strogatz_graph(
    10,
    3,
    self.p.network_randomness)